document.body.querySelectorAll("a[data-amp-cur]").forEach((element) => {
  const anchor = element as HTMLAnchorElement;
  console.debug("Adding onclick handler to AMP anchor", anchor);

  anchor.onclick = (event) => {
    const finalURL = anchor.dataset.ampCur;

    if (!finalURL) {
      return;
    }

    event.stopImmediatePropagation();

    if (window.location.pathname.startsWith("/amp/s/")) {
      console.log("Replacing loaded AMP URL");
      window.location.replace(finalURL);
    } else {
      console.log("Pushing non-AMP URL");
      window.location.assign(finalURL);
    }

    browser.runtime.sendNativeMessage("this.is.ignored", {
      ampURL: anchor.href,
      finalURL: finalURL,
    });

    return false;
  };
});

const ampPrefixes = [
  "https://www.google.com/amp/s/*",
  "https://www.google.ad/amp/s/*",
  "https://www.google.ae/amp/s/*",
  "https://www.google.com.af/amp/s/*",
  "https://www.google.com.ag/amp/s/*",
  "https://www.google.com.ai/amp/s/*",
  "https://www.google.al/amp/s/*",
  "https://www.google.am/amp/s/*",
  "https://www.google.co.ao/amp/s/*",
  "https://www.google.com.ar/amp/s/*",
  "https://www.google.as/amp/s/*",
  "https://www.google.at/amp/s/*",
  "https://www.google.com.au/amp/s/*",
  "https://www.google.az/amp/s/*",
  "https://www.google.ba/amp/s/*",
  "https://www.google.com.bd/amp/s/*",
  "https://www.google.be/amp/s/*",
  "https://www.google.bf/amp/s/*",
  "https://www.google.bg/amp/s/*",
  "https://www.google.com.bh/amp/s/*",
  "https://www.google.bi/amp/s/*",
  "https://www.google.bj/amp/s/*",
  "https://www.google.com.bn/amp/s/*",
  "https://www.google.com.bo/amp/s/*",
  "https://www.google.com.br/amp/s/*",
  "https://www.google.bs/amp/s/*",
  "https://www.google.bt/amp/s/*",
  "https://www.google.co.bw/amp/s/*",
  "https://www.google.by/amp/s/*",
  "https://www.google.com.bz/amp/s/*",
  "https://www.google.ca/amp/s/*",
  "https://www.google.cd/amp/s/*",
  "https://www.google.cf/amp/s/*",
  "https://www.google.cg/amp/s/*",
  "https://www.google.ch/amp/s/*",
  "https://www.google.ci/amp/s/*",
  "https://www.google.co.ck/amp/s/*",
  "https://www.google.cl/amp/s/*",
  "https://www.google.cm/amp/s/*",
  "https://www.google.cn/amp/s/*",
  "https://www.google.com.co/amp/s/*",
  "https://www.google.co.cr/amp/s/*",
  "https://www.google.com.cu/amp/s/*",
  "https://www.google.cv/amp/s/*",
  "https://www.google.com.cy/amp/s/*",
  "https://www.google.cz/amp/s/*",
  "https://www.google.de/amp/s/*",
  "https://www.google.dj/amp/s/*",
  "https://www.google.dk/amp/s/*",
  "https://www.google.dm/amp/s/*",
  "https://www.google.com.do/amp/s/*",
  "https://www.google.dz/amp/s/*",
  "https://www.google.com.ec/amp/s/*",
  "https://www.google.ee/amp/s/*",
  "https://www.google.com.eg/amp/s/*",
  "https://www.google.es/amp/s/*",
  "https://www.google.com.et/amp/s/*",
  "https://www.google.fi/amp/s/*",
  "https://www.google.com.fj/amp/s/*",
  "https://www.google.fm/amp/s/*",
  "https://www.google.fr/amp/s/*",
  "https://www.google.ga/amp/s/*",
  "https://www.google.ge/amp/s/*",
  "https://www.google.gg/amp/s/*",
  "https://www.google.com.gh/amp/s/*",
  "https://www.google.com.gi/amp/s/*",
  "https://www.google.gl/amp/s/*",
  "https://www.google.gm/amp/s/*",
  "https://www.google.gr/amp/s/*",
  "https://www.google.com.gt/amp/s/*",
  "https://www.google.gy/amp/s/*",
  "https://www.google.com.hk/amp/s/*",
  "https://www.google.hn/amp/s/*",
  "https://www.google.hr/amp/s/*",
  "https://www.google.ht/amp/s/*",
  "https://www.google.hu/amp/s/*",
  "https://www.google.co.id/amp/s/*",
  "https://www.google.ie/amp/s/*",
  "https://www.google.co.il/amp/s/*",
  "https://www.google.im/amp/s/*",
  "https://www.google.co.in/amp/s/*",
  "https://www.google.iq/amp/s/*",
  "https://www.google.is/amp/s/*",
  "https://www.google.it/amp/s/*",
  "https://www.google.je/amp/s/*",
  "https://www.google.com.jm/amp/s/*",
  "https://www.google.jo/amp/s/*",
  "https://www.google.co.jp/amp/s/*",
  "https://www.google.co.ke/amp/s/*",
  "https://www.google.com.kh/amp/s/*",
  "https://www.google.ki/amp/s/*",
  "https://www.google.kg/amp/s/*",
  "https://www.google.co.kr/amp/s/*",
  "https://www.google.com.kw/amp/s/*",
  "https://www.google.kz/amp/s/*",
  "https://www.google.la/amp/s/*",
  "https://www.google.com.lb/amp/s/*",
  "https://www.google.li/amp/s/*",
  "https://www.google.lk/amp/s/*",
  "https://www.google.co.ls/amp/s/*",
  "https://www.google.lt/amp/s/*",
  "https://www.google.lu/amp/s/*",
  "https://www.google.lv/amp/s/*",
  "https://www.google.com.ly/amp/s/*",
  "https://www.google.co.ma/amp/s/*",
  "https://www.google.md/amp/s/*",
  "https://www.google.me/amp/s/*",
  "https://www.google.mg/amp/s/*",
  "https://www.google.mk/amp/s/*",
  "https://www.google.ml/amp/s/*",
  "https://www.google.com.mm/amp/s/*",
  "https://www.google.mn/amp/s/*",
  "https://www.google.ms/amp/s/*",
  "https://www.google.com.mt/amp/s/*",
  "https://www.google.mu/amp/s/*",
  "https://www.google.mv/amp/s/*",
  "https://www.google.mw/amp/s/*",
  "https://www.google.com.mx/amp/s/*",
  "https://www.google.com.my/amp/s/*",
  "https://www.google.co.mz/amp/s/*",
  "https://www.google.com.na/amp/s/*",
  "https://www.google.com.ng/amp/s/*",
  "https://www.google.com.ni/amp/s/*",
  "https://www.google.ne/amp/s/*",
  "https://www.google.nl/amp/s/*",
  "https://www.google.no/amp/s/*",
  "https://www.google.com.np/amp/s/*",
  "https://www.google.nr/amp/s/*",
  "https://www.google.nu/amp/s/*",
  "https://www.google.co.nz/amp/s/*",
  "https://www.google.com.om/amp/s/*",
  "https://www.google.com.pa/amp/s/*",
  "https://www.google.com.pe/amp/s/*",
  "https://www.google.com.pg/amp/s/*",
  "https://www.google.com.ph/amp/s/*",
  "https://www.google.com.pk/amp/s/*",
  "https://www.google.pl/amp/s/*",
  "https://www.google.pn/amp/s/*",
  "https://www.google.com.pr/amp/s/*",
  "https://www.google.ps/amp/s/*",
  "https://www.google.pt/amp/s/*",
  "https://www.google.com.py/amp/s/*",
  "https://www.google.com.qa/amp/s/*",
  "https://www.google.ro/amp/s/*",
  "https://www.google.ru/amp/s/*",
  "https://www.google.rw/amp/s/*",
  "https://www.google.com.sa/amp/s/*",
  "https://www.google.com.sb/amp/s/*",
  "https://www.google.sc/amp/s/*",
  "https://www.google.se/amp/s/*",
  "https://www.google.com.sg/amp/s/*",
  "https://www.google.sh/amp/s/*",
  "https://www.google.si/amp/s/*",
  "https://www.google.sk/amp/s/*",
  "https://www.google.com.sl/amp/s/*",
  "https://www.google.sn/amp/s/*",
  "https://www.google.so/amp/s/*",
  "https://www.google.sm/amp/s/*",
  "https://www.google.sr/amp/s/*",
  "https://www.google.st/amp/s/*",
  "https://www.google.com.sv/amp/s/*",
  "https://www.google.td/amp/s/*",
  "https://www.google.tg/amp/s/*",
  "https://www.google.co.th/amp/s/*",
  "https://www.google.com.tj/amp/s/*",
  "https://www.google.tl/amp/s/*",
  "https://www.google.tm/amp/s/*",
  "https://www.google.tn/amp/s/*",
  "https://www.google.to/amp/s/*",
  "https://www.google.com.tr/amp/s/*",
  "https://www.google.tt/amp/s/*",
  "https://www.google.com.tw/amp/s/*",
  "https://www.google.co.tz/amp/s/*",
  "https://www.google.com.ua/amp/s/*",
  "https://www.google.co.ug/amp/s/*",
  "https://www.google.co.uk/amp/s/*",
  "https://www.google.com.uy/amp/s/*",
  "https://www.google.co.uz/amp/s/*",
  "https://www.google.com.vc/amp/s/*",
  "https://www.google.co.ve/amp/s/*",
  "https://www.google.vg/amp/s/*",
  "https://www.google.co.vi/amp/s/*",
  "https://www.google.com.vn/amp/s/*",
  "https://www.google.vu/amp/s/*",
  "https://www.google.ws/amp/s/*",
  "https://www.google.rs/amp/s/*",
  "https://www.google.co.za/amp/s/*",
  "https://www.google.co.zm/amp/s/*",
  "https://www.google.co.zw/amp/s/*",
  "https://www.google.cat/amp/s/*",
];
