default_platform :ios

setup_ci

platform :ios do
  desc "Submit a new iOS build to TestFlight"
  lane :submit_beta do
    setup_app_store_connect_api_key

    whats_new = ""

    if File.exists?("./metadata/testflight_whats_new.txt")
      whats_new = File.read("./metadata/testflight_whats_new.txt")
    end

    if whats_new.strip.empty?
      whats_new = File.read("./metadata/default/release_notes.txt")
    end

    download_certs

    increment_build_number({
      build_number: latest_testflight_build_number + 1
    })

    gym

    pilot(
      distribute_external: false,
      groups: [
        "Priority",
      ],
      beta_app_review_info: {
        contact_first_name: "Joseph",
        contact_last_name: "Duffy",
        demo_account_name: "",
        demo_account_password: "",
        notes: "A demo video of the extension: https://www.icloud.com/iclouddrive/0CrIK3GXyer7_XpcMC4vUq27A#App_Review_Demo

Overamped is not enabled at the start of the video. Note how tapping the news result in Google opens the AMP version of the page (website is hosted by Google, shows actual website domain at top, the website is missing some features such as the navigation menu). Once the extension has been enabled and the page refresh tapping the same link instead loads the original page."
      },
      localized_app_info: {
        "default": {
          feedback_email: "joseph@yetii.net",
          marketing_url: "https://overamped.app",
          privacy_policy_url: "https://overamped.app/privacy",
          description: "",
        },
      },
      localized_build_info: {
        "default": {
          whats_new: whats_new,
        }
      }
    )
  end

  desc "Upload metadata the App Store"
  lane :upload_metadata do
    setup_app_store_connect_api_key
    deliver(platform: "ios", skip_binary_upload: true, skip_screenshots: is_ci)
  end

  desc "Generate and frame App Store screenshots"
  lane :generate_screenshots do
    capture_screenshots
  end

  desc "Download iOS certificates (read only)"
  lane :download_certs do
    if !is_ci
      setup_app_store_connect_api_key
    end

    match()
  end

  desc "Download iOS certificates, generating any missing profiles"
  lane :download_or_generate_certs do
    if !is_ci
      setup_app_store_connect_api_key
    end

    match(readonly: false)
  end

  desc "Force recreation of iOS certificates"
  lane :generate_certs do
    setup_app_store_connect_api_key
    match(
      readonly: false,
      force: true
    )
  end
end

private_lane :setup_app_store_connect_api_key do
  # This action looks for specific environment variables, which allows for both local and CI use.
  # See `fastlane action app_store_connect_api_key` for expected environment variable names.
  app_store_connect_api_key(in_house: false)
end