name: Push

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build app
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Use Xcode 14.1
        run: sudo xcode-select --switch /Applications/Xcode_14.1.app

      - name: Install Ruby and fastlane
        uses: ruby/setup-ruby@v1
        with:
          # Version is read from .ruby-version
          bundler-cache: true

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version-file: "./Overamped Extension/Resources/.node-version"

      - name: Download certs
        run: bundle exec fastlane download_certs
        env:
          MATCH_GIT_PRIVATE_KEY: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

      - name: Build
        run: bundle exec fastlane gym
