name: Push

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build app
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4

      - name: Use Xcode 16.4
        run: sudo xcode-select --switch /Applications/Xcode_16.4.app

      - name: Install Ruby and fastlane
        uses: ruby/setup-ruby@v1
        with:
          # Version is read from .tool-versions
          bundler-cache: true

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version-file: "./Overamped Extension/Resources/.tool-versions"

      - name: Download certs
        run: bundle exec fastlane download_certs
        env:
          MATCH_GIT_PRIVATE_KEY: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

      - name: Build
        run: bundle exec fastlane gym
