name: Upload to TestFlight

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  upload:
    name: Upload to App Store Connect
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Use Xcode 14.1
        run: sudo xcode-select --switch /Applications/Xcode_14.1.app

      - name: Install Ruby and fastlane
        uses: ruby/setup-ruby@v1
        with:
          # Version is read from .ruby-version
          bundler-cache: true

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version-file: "./Overamped Extension/Resources/.node-version"

      - run: bundle exec fastlane submit_beta
        env:
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
          APP_STORE_CONNECT_API_KEY_IS_KEY_CONTENT_BASE64: "true"
          MATCH_GIT_PRIVATE_KEY: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

      - run: bundle exec fastlane upload_metadata
        env:
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
          APP_STORE_CONNECT_API_KEY_IS_KEY_CONTENT_BASE64: "true"
