name: Upload to TestFlight

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  upload:
    name: Upload to App Store Connect
    runs-on: macos-15
    env:
      APP_STORE_APPLE_ID: ${{ vars.APP_STORE_APPLE_ID }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Xcode 16.4
        run: sudo xcode-select --switch /Applications/Xcode_16.4.app

      - name: Install Ruby and fastlane
        uses: ruby/setup-ruby@v1
        with:
          # Version is read from .tool-versions
          bundler-cache: true

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version-file: "./Overamped Extension/Resources/.tool-versions"

      - name: Install Codemagic CLI tools
        run: pip install codemagic-cli-tools

      - name: Set up keychain
        run: keychain initialize

      - name: Fetch signing files
        env:
          APP_STORE_CONNECT_ISSUER_ID: ${{ vars.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_KEY_IDENTIFIER: ${{ vars.APP_STORE_CONNECT_KEY_IDENTIFIER }}
          APP_STORE_CONNECT_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}
          CERTIFICATE_PRIVATE_KEY: ${{ secrets.CERTIFICATE_PRIVATE_KEY }}
        run: |
          app-store-connect fetch-signing-files $(xcode-project detect-bundle-id) \
            --type IOS_APP_STORE \
            --create

      - name: Set up signing certificate
        run: keychain add-certificates

      - name: Set up code signing settings on Xcode project
        run: xcode-project use-profiles

      - run: bundle exec fastlane submit_beta
        env:
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
          APP_STORE_CONNECT_API_KEY_IS_KEY_CONTENT_BASE64: "true"

      - run: bundle exec fastlane upload_metadata
        env:
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
          APP_STORE_CONNECT_API_KEY_IS_KEY_CONTENT_BASE64: "true"

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        with:
          detached: true
